// =============================================================================
// Error Codes Registry - Unified Error Code Definitions
// =============================================================================

/**
 * Authentication error codes (AUTH_*)
 * Used for authentication-related failures
 */
export enum AuthErrorCode {
  // Token errors
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID = 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_MISSING = 'AUTH_TOKEN_MISSING',
  AUTH_TOKEN_REVOKED = 'AUTH_TOKEN_REVOKED',
  AUTH_REFRESH_TOKEN_EXPIRED = 'AUTH_REFRESH_TOKEN_EXPIRED',
  AUTH_REFRESH_TOKEN_INVALID = 'AUTH_REFRESH_TOKEN_INVALID',

  // Credential errors
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_INVALID_PASSWORD = 'AUTH_INVALID_PASSWORD',
  AUTH_PASSWORD_MISMATCH = 'AUTH_PASSWORD_MISMATCH',
  AUTH_PASSWORD_TOO_WEAK = 'AUTH_PASSWORD_TOO_WEAK',

  // Account errors
  AUTH_ACCOUNT_LOCKED = 'AUTH_ACCOUNT_LOCKED',
  AUTH_ACCOUNT_DISABLED = 'AUTH_ACCOUNT_DISABLED',
  AUTH_ACCOUNT_NOT_VERIFIED = 'AUTH_ACCOUNT_NOT_VERIFIED',
  AUTH_ACCOUNT_SUSPENDED = 'AUTH_ACCOUNT_SUSPENDED',
  AUTH_EMAIL_NOT_VERIFIED = 'AUTH_EMAIL_NOT_VERIFIED',

  // MFA errors
  AUTH_MFA_REQUIRED = 'AUTH_MFA_REQUIRED',
  AUTH_MFA_INVALID_CODE = 'AUTH_MFA_INVALID_CODE',
  AUTH_MFA_SETUP_REQUIRED = 'AUTH_MFA_SETUP_REQUIRED',

  // Session errors
  AUTH_SESSION_EXPIRED = 'AUTH_SESSION_EXPIRED',
  AUTH_SESSION_INVALID = 'AUTH_SESSION_INVALID',
  AUTH_SESSION_LIMIT_EXCEEDED = 'AUTH_SESSION_LIMIT_EXCEEDED',

  // OAuth errors
  AUTH_OAUTH_FAILED = 'AUTH_OAUTH_FAILED',
  AUTH_OAUTH_ACCOUNT_EXISTS = 'AUTH_OAUTH_ACCOUNT_EXISTS',
  AUTH_OAUTH_PROVIDER_ERROR = 'AUTH_OAUTH_PROVIDER_ERROR',
  AUTH_OAUTH_TOKEN_EXCHANGE_FAILED = 'AUTH_OAUTH_TOKEN_EXCHANGE_FAILED',
}

/**
 * Authorization error codes (AUTHZ_*)
 * Used for permission and access control failures
 */
export enum AuthorizationErrorCode {
  AUTHZ_FORBIDDEN = 'AUTHZ_FORBIDDEN',
  AUTHZ_INSUFFICIENT_PERMISSIONS = 'AUTHZ_INSUFFICIENT_PERMISSIONS',
  AUTHZ_ROLE_REQUIRED = 'AUTHZ_ROLE_REQUIRED',
  AUTHZ_RESOURCE_ACCESS_DENIED = 'AUTHZ_RESOURCE_ACCESS_DENIED',
  AUTHZ_ORGANIZATION_ACCESS_DENIED = 'AUTHZ_ORGANIZATION_ACCESS_DENIED',
  AUTHZ_SUBSCRIPTION_REQUIRED = 'AUTHZ_SUBSCRIPTION_REQUIRED',
  AUTHZ_FEATURE_DISABLED = 'AUTHZ_FEATURE_DISABLED',
  AUTHZ_QUOTA_EXCEEDED = 'AUTHZ_QUOTA_EXCEEDED',
}

/**
 * Validation error codes (VALIDATION_*)
 * Used for input validation failures
 */
export enum ValidationErrorCode {
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  VALIDATION_REQUIRED_FIELD = 'VALIDATION_REQUIRED_FIELD',
  VALIDATION_INVALID_FORMAT = 'VALIDATION_INVALID_FORMAT',
  VALIDATION_INVALID_TYPE = 'VALIDATION_INVALID_TYPE',
  VALIDATION_INVALID_LENGTH = 'VALIDATION_INVALID_LENGTH',
  VALIDATION_INVALID_RANGE = 'VALIDATION_INVALID_RANGE',
  VALIDATION_INVALID_ENUM = 'VALIDATION_INVALID_ENUM',
  VALIDATION_INVALID_EMAIL = 'VALIDATION_INVALID_EMAIL',
  VALIDATION_INVALID_URL = 'VALIDATION_INVALID_URL',
  VALIDATION_INVALID_UUID = 'VALIDATION_INVALID_UUID',
  VALIDATION_INVALID_DATE = 'VALIDATION_INVALID_DATE',
  VALIDATION_INVALID_JSON = 'VALIDATION_INVALID_JSON',
  VALIDATION_INVALID_FILE = 'VALIDATION_INVALID_FILE',
  VALIDATION_FILE_TOO_LARGE = 'VALIDATION_FILE_TOO_LARGE',
  VALIDATION_FILE_TYPE_NOT_ALLOWED = 'VALIDATION_FILE_TYPE_NOT_ALLOWED',
  VALIDATION_ARRAY_TOO_LONG = 'VALIDATION_ARRAY_TOO_LONG',
  VALIDATION_ARRAY_TOO_SHORT = 'VALIDATION_ARRAY_TOO_SHORT',
  VALIDATION_DUPLICATE_VALUE = 'VALIDATION_DUPLICATE_VALUE',
  VALIDATION_CONSTRAINT_VIOLATION = 'VALIDATION_CONSTRAINT_VIOLATION',
}

/**
 * Resource error codes (RESOURCE_*)
 * Used for resource-related failures
 */
export enum ResourceErrorCode {
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  RESOURCE_ALREADY_EXISTS = 'RESOURCE_ALREADY_EXISTS',
  RESOURCE_DELETED = 'RESOURCE_DELETED',
  RESOURCE_LOCKED = 'RESOURCE_LOCKED',
  RESOURCE_CONFLICT = 'RESOURCE_CONFLICT',
  RESOURCE_VERSION_CONFLICT = 'RESOURCE_VERSION_CONFLICT',
  RESOURCE_LIMIT_EXCEEDED = 'RESOURCE_LIMIT_EXCEEDED',
  RESOURCE_QUOTA_EXCEEDED = 'RESOURCE_QUOTA_EXCEEDED',
  RESOURCE_DEPENDENCY_ERROR = 'RESOURCE_DEPENDENCY_ERROR',
  RESOURCE_INVALID_STATE = 'RESOURCE_INVALID_STATE',
  RESOURCE_OPERATION_NOT_ALLOWED = 'RESOURCE_OPERATION_NOT_ALLOWED',
}

/**
 * Business logic error codes (BUSINESS_*)
 * Used for business rule violations
 */
export enum BusinessErrorCode {
  BUSINESS_RULE_VIOLATION = 'BUSINESS_RULE_VIOLATION',
  BUSINESS_CAMPAIGN_INACTIVE = 'BUSINESS_CAMPAIGN_INACTIVE',
  BUSINESS_CAMPAIGN_CLOSED = 'BUSINESS_CAMPAIGN_CLOSED',
  BUSINESS_CAMPAIGN_FULL = 'BUSINESS_CAMPAIGN_FULL',
  BUSINESS_APPLICATION_ALREADY_EXISTS = 'BUSINESS_APPLICATION_ALREADY_EXISTS',
  BUSINESS_APPLICATION_NOT_ELIGIBLE = 'BUSINESS_APPLICATION_NOT_ELIGIBLE',
  BUSINESS_DELIVERABLE_DEADLINE_PASSED = 'BUSINESS_DELIVERABLE_DEADLINE_PASSED',
  BUSINESS_CONTENT_NOT_APPROVED = 'BUSINESS_CONTENT_NOT_APPROVED',
  BUSINESS_PAYMENT_FAILED = 'BUSINESS_PAYMENT_FAILED',
  BUSINESS_INSUFFICIENT_BALANCE = 'BUSINESS_INSUFFICIENT_BALANCE',
  BUSINESS_WITHDRAWAL_LIMIT_EXCEEDED = 'BUSINESS_WITHDRAWAL_LIMIT_EXCEEDED',
  BUSINESS_CREATOR_NOT_VERIFIED = 'BUSINESS_CREATOR_NOT_VERIFIED',
  BUSINESS_STORE_NOT_CONNECTED = 'BUSINESS_STORE_NOT_CONNECTED',
  BUSINESS_PRODUCT_UNAVAILABLE = 'BUSINESS_PRODUCT_UNAVAILABLE',
}

/**
 * External service error codes (EXTERNAL_*)
 * Used for third-party service failures
 */
export enum ExternalServiceErrorCode {
  EXTERNAL_SERVICE_ERROR = 'EXTERNAL_SERVICE_ERROR',
  EXTERNAL_SERVICE_UNAVAILABLE = 'EXTERNAL_SERVICE_UNAVAILABLE',
  EXTERNAL_SERVICE_TIMEOUT = 'EXTERNAL_SERVICE_TIMEOUT',
  EXTERNAL_API_ERROR = 'EXTERNAL_API_ERROR',
  EXTERNAL_API_RATE_LIMITED = 'EXTERNAL_API_RATE_LIMITED',
  EXTERNAL_PAYMENT_PROVIDER_ERROR = 'EXTERNAL_PAYMENT_PROVIDER_ERROR',
  EXTERNAL_STORAGE_ERROR = 'EXTERNAL_STORAGE_ERROR',
  EXTERNAL_EMAIL_DELIVERY_FAILED = 'EXTERNAL_EMAIL_DELIVERY_FAILED',
  EXTERNAL_SMS_DELIVERY_FAILED = 'EXTERNAL_SMS_DELIVERY_FAILED',
  EXTERNAL_WEBHOOK_DELIVERY_FAILED = 'EXTERNAL_WEBHOOK_DELIVERY_FAILED',
  EXTERNAL_AI_SERVICE_ERROR = 'EXTERNAL_AI_SERVICE_ERROR',
  EXTERNAL_SOCIAL_PLATFORM_ERROR = 'EXTERNAL_SOCIAL_PLATFORM_ERROR',
  EXTERNAL_ECOMMERCE_PLATFORM_ERROR = 'EXTERNAL_ECOMMERCE_PLATFORM_ERROR',
}

/**
 * Rate limit error codes (RATE_LIMIT_*)
 * Used for rate limiting failures
 */
export enum RateLimitErrorCode {
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  RATE_LIMIT_IP_EXCEEDED = 'RATE_LIMIT_IP_EXCEEDED',
  RATE_LIMIT_USER_EXCEEDED = 'RATE_LIMIT_USER_EXCEEDED',
  RATE_LIMIT_API_KEY_EXCEEDED = 'RATE_LIMIT_API_KEY_EXCEEDED',
  RATE_LIMIT_ENDPOINT_EXCEEDED = 'RATE_LIMIT_ENDPOINT_EXCEEDED',
}

/**
 * Server error codes (SERVER_*)
 * Used for internal server errors
 */
export enum ServerErrorCode {
  SERVER_INTERNAL_ERROR = 'SERVER_INTERNAL_ERROR',
  SERVER_DATABASE_ERROR = 'SERVER_DATABASE_ERROR',
  SERVER_CACHE_ERROR = 'SERVER_CACHE_ERROR',
  SERVER_QUEUE_ERROR = 'SERVER_QUEUE_ERROR',
  SERVER_CONFIGURATION_ERROR = 'SERVER_CONFIGURATION_ERROR',
  SERVER_MAINTENANCE_MODE = 'SERVER_MAINTENANCE_MODE',
  SERVER_OVERLOADED = 'SERVER_OVERLOADED',
  SERVER_NOT_IMPLEMENTED = 'SERVER_NOT_IMPLEMENTED',
  SERVER_FEATURE_DISABLED = 'SERVER_FEATURE_DISABLED',
}

/**
 * File/Media error codes (MEDIA_*)
 * Used for file and media processing failures
 */
export enum MediaErrorCode {
  MEDIA_UPLOAD_FAILED = 'MEDIA_UPLOAD_FAILED',
  MEDIA_PROCESSING_FAILED = 'MEDIA_PROCESSING_FAILED',
  MEDIA_ENCODING_FAILED = 'MEDIA_ENCODING_FAILED',
  MEDIA_TRANSCODING_FAILED = 'MEDIA_TRANSCODING_FAILED',
  MEDIA_THUMBNAIL_GENERATION_FAILED = 'MEDIA_THUMBNAIL_GENERATION_FAILED',
  MEDIA_INVALID_FORMAT = 'MEDIA_INVALID_FORMAT',
  MEDIA_CORRUPTED = 'MEDIA_CORRUPTED',
  MEDIA_TOO_LARGE = 'MEDIA_TOO_LARGE',
  MEDIA_DURATION_TOO_LONG = 'MEDIA_DURATION_TOO_LONG',
  MEDIA_RESOLUTION_TOO_HIGH = 'MEDIA_RESOLUTION_TOO_HIGH',
  MEDIA_NOT_FOUND = 'MEDIA_NOT_FOUND',
  MEDIA_ACCESS_DENIED = 'MEDIA_ACCESS_DENIED',
}

/**
 * Union type of all error codes
 */
export type ErrorCode =
  | AuthErrorCode
  | AuthorizationErrorCode
  | ValidationErrorCode
  | ResourceErrorCode
  | BusinessErrorCode
  | ExternalServiceErrorCode
  | RateLimitErrorCode
  | ServerErrorCode
  | MediaErrorCode;

/**
 * All error codes as a single object for easy access
 */
export const ErrorCodes = {
  ...AuthErrorCode,
  ...AuthorizationErrorCode,
  ...ValidationErrorCode,
  ...ResourceErrorCode,
  ...BusinessErrorCode,
  ...ExternalServiceErrorCode,
  ...RateLimitErrorCode,
  ...ServerErrorCode,
  ...MediaErrorCode,
} as const;
